### ISSUE TITLE
some try

### ISSUE THREAD

**Issue by 0815Unbekannt** [mrwan84/SVGHMIC#1]
I've made some changes here, do whatever you want with the code. It's not finished yet, but it has more than your first version.

i used vkbeautify for prettyView
Home page: http://www.eslinstructor.net/vkbeautify/

[SVGHMIC.zip](https://github.com/mrwan84/SVGHMIC/files/12880864/SVGHMIC.zip)

**Comment by mrwan84** [comment]
super.
Thank you
